### PR TITLE
Fix Quirion dividend import in USD

### PR DESCRIPTION
**Pull request by buchen**
Issue: #3474

[rebased to master]

### CODE REVIEW

**Comment by buchen** [comment]
(sorry, I had to close and reopen the pull request because of a naming conflict of this PR and the branches automatically created for pull requests)

**Comment by buchen** [comment]
Copying the conversation over from #3475 

@Nirus2000 asked:
> I don't understand this pull request at all.
> What is changed here and why are useless parts inserted?

**Comment by buchen** [comment]
I let @christen90 comment on the details.

But what I can see is that the "Dividende04.txt" example **cannot** be imported without the changes to the extractor.

```
Failures:
  QuirinPrivatbankAGPDFExtractorTest.testDividende04:592 Buchungswährung USD passt nicht zu Kontowährung EUR
26.07.2023 Dividende USD 1,57 iShsIII-MSCI EM Sm.Cap U.ETF Registered Shares o.N. Dividende04.txt
Expected: is <OK>
     but: was <ERROR>
```

My reading of the change is: like many other sections that have different format (there are already many Format01 and Format02 methods), there apparently is also a differences is the formatting of the "taxes sections".


> What is changed here and why are useless parts inserted?

Can you specify what you mean by "useless parts"?

**Comment by Nirus2000** [comment]
@buchen @christen90 
It goes with the pull request a bissl under and over, 
I take up now and convert this again.

Due to the move to the ORGA, these are also new procedures for us, how we deal with PR's and your commit is basically correct and I'm cleaning it up now.

**Pull request closed without merging**
