### PR TITLE
Fix Quirion dividend import in USD

### PR DESCRIPTION
**Pull request by buchen**
Issue: #3474

### CODE REVIEW

**Comment by buchen** [comment]
@christen90 - apparently, I had to create a new pull request. Please have a look at your change - I might have mangled up something... 🙄

**Comment by Nirus2000** [comment]
I don't understand this pull request at all.
What is changed here and why are useless parts inserted?

**Comment by buchen** [comment]
I let @christen90 comment on the details.

But what I can see is that the "Dividende04.txt" example **cannot** be imported without the changes to the extractor.

```
Failures:
  QuirinPrivatbankAGPDFExtractorTest.testDividende04:592 Buchungswährung USD passt nicht zu Kontowährung EUR
26.07.2023 Dividende USD 1,57 iShsIII-MSCI EM Sm.Cap U.ETF Registered Shares o.N. Dividende04.txt
Expected: is <OK>
     but: was <ERROR>
```

My reading of the change is: like many other sections that have different format (there are already many Format01 and Format02 methods), there apparently is also a differences is the formatting of the "taxes sections".


> What is changed here and why are useless parts inserted?

Can you specify what you mean by "useless parts"?

**Comment by buchen** [comment]
Let's continue here: #3482

**Pull request closed without merging**
