### PR TITLE
Use Java ImageIO library to resize logo images to keep transparency intact

### PR DESCRIPTION
**Pull request by buchen**
Issue: #3619

### CODE REVIEW

**Comment by buchen** [comment]
@OnkelDok @Nirus2000 if one of you has time, I would be interested in feedback how it looks on Windows (and in dark mode).

The changed functionality is only applied to newly imported logos (the others have already been scaled with the old code). If you want to test it, you can use the BAYER logo from #3619

**Comment by buchen** [comment]
Test on **Linux aarch64 (Fedora)**

Apparently, there are Linux distributions that install the "headless" package that does not include the native libraries for ImageIO. See this Stackoverflow issue for details: https://stackoverflow.com/questions/67391845/exception-java-lang-unsatisfiedlinkerror-when-trying-to-open-allure-reports-in-w

```
Ein Fehler ist aufgetreten. Details finden Sie im Fehlerprotokoll.
Can't load library: /usr/lib/jvm/java-17-openjdk-17.0.5.0.8-1.fc37.aarch64/lib/libawt_xawt.so
```

```
java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
	at name.abuchen.portfolio.util.ImageUtil.loadAndPrepare(ImageUtil.java:137)
	at name.abuchen.portfolio.ui.wizards.security.AttributesPage.lambda$1(AttributesPage.java:232)
	at org.eclipse.swt.events.MouseListener$2.mouseDown(MouseListener.java:96)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at name.abuchen.portfolio.ui.views.SecuritiesTable$AbstractDialogAction.run(SecuritiesTable.java:1174)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
```

**Comment by buchen** [comment]
About Fedora, aarch64 - if I install the full JDK, it works

Bildschirmfoto 2023-11-12 um 20 39 06
Bildschirmfoto 2023-11-12 um 20 39 18

**Comment by buchen** [comment]
And one final comment: when installed via flatpak, the full JRE installed including the ImageIO native libraries

I think the best course of action is to try to use ImageIO and, if not available, fall back to the existing code

**Comment by Nirus2000** [comment]
Hello @buchen 
I have looked at the pull request. 

### The following results.
grafik


#### Light theme:
We should remove the hover... :smile::smile::smile:
grafik
grafik

#### Dark theme:
grafik

**Comment by buchen** [comment]
> We should remove the hover... 😄😄😄

:-)

**Comment by buchen** [comment]
Merged with e033cd20c3cfec964f334287aa646b81c01772ef

Implemented a fallback to existing SWT code if ImageIO library is not available on the system.

**Pull request closed without merging**
