### PR TITLE
Adds option for non cash-effective dividend payments.

### PR DESCRIPTION
**Pull request by Pnda87**
Payments marked as such can be excluded in the payments
report to display only cash effective transactions.

issue: #2970

### CODE REVIEW

**Comment by Nirus2000** [comment]
Hello @Pnda87 
would it be possible to add a few more TestCases and the missing translations?

If we look under all transactions and sort by dividends as an example, how are they identified? 🤔 

Greetings
Alex

**Comment by Pnda87** [comment]
In my opinion, they dont need to be identifiable under all transactions as the option is not applicable to 99% of all transactions.
If the option is set or not can be seen in the edit dialog of the specific dividend transaction

rg. translations: EN+DE is there, the other languages shall ideally be done by natives.

**Comment by Nirus2000** [comment]
Let's say I have 100 divide transactions and have disabled several of them but forgot which ones, that would be very tedious for the user to always call up 100 transactions to see if it has been disabled.

**Comment by Pnda87** [comment]
I rebased the code on the current master and refined it a bit more. cf. #3610

**Pull request closed without merging**
