### PR TITLE
new PDF Importer for "MeineBank" / RaiBa Hochtaunus

### PR DESCRIPTION
**Pull request by ZfT2**
support "MeineBank" Tagesgeldkonto-Auszüge

### CODE REVIEW

**Comment by Nirus2000** [comment]
Hello @ZfT2 
I don't think we need this importer as a Raifeisenbank PDF importer already exists.
See [RaiffeisenBankgruppePDFExtractor().java](https://github.com/portfolio-performance/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/RaiffeisenBankgruppePDFExtractor.java)
Please customize this importer.

Regards
Alex

**Comment by ZfT2** [comment]
Thank you, I didn't notice that there is already a "generic" Raiffeisenbank PDF importer... I will try your suggested changes soon.

**Comment by ZfT2** [comment]
I integrated it in the existing Raiffeisenbank Importer now.

**Comment by Nirus2000** [comment]
Perfect... Good job! 👍🏻

**Pull request merged**
