### PR TITLE
Modify kbc group nv pdf importer to support

### PR DESCRIPTION
**Pull request by Nirus2000**
https://forum.portfolio-performance.info/t/pdf-import-from-kbc-bank-nv/22455/10
https://forum.portfolio-performance.info/t/pdf-import-from-kbc-bank-nv/22455/11

### CODE REVIEW

**Comment by Nirus2000** [comment]
Hey @buchen 
I see the problem. As soon as we have two booking currencies, the test cases fail.
We once made this change so that all currencies that we identify as booking currencies are checked and accepted and, if missing booking currencies are recognized, an error is thrown.
It should also be recognized that if I insert an incorrect currency, e.g. “ZAR” here, but there is no transaction, this should also be output with a message.

### Single currency:
`new AssertImportActions().check(results, “EUR”);`

### Multiple currency:
`new AssertImportActions().check(results, “EUR”, “USD”);`

---
### Thats i want
`new AssertImportActions().check(results, hasCurrencyCodes("EUR", "USD"));`

with.... ExtractorMatchers.java like
```
@SafeVarargs
public static Matcher<Transaction> hasCurrencyCodes(String... currencyCodes) {
    return new TypeSafeDiagnosingMatcher<Transaction>() {
        @Override
        protected boolean matchesSafely(Transaction transaction, Description mismatchDescription) {
            String currencyCode = transaction.getMonetaryAmount().getCurrencyCode();
            boolean codeFound = false;

            for (String code : currencyCodes) {
                if (code.equals(currencyCode)) {
                    codeFound = true;
                    break;
                }
            }

            if (!codeFound) {
                mismatchDescription.appendText("currencyCode was ").appendText(currencyCode);
                return false;
            }

            // If the currency code is found, we can ensure there's a corresponding transaction
            boolean hasMatchingTransaction = results.stream()
                .filter(item -> item instanceof TransactionItem)
                .anyMatch(item -> {
                    Transaction trans = ((TransactionItem) item).getSubject();
                    return trans.getMonetaryAmount().getCurrencyCode().equals(currencyCode);
                });

            if (!hasMatchingTransaction) {
                mismatchDescription.appendText("but no matching transaction found for currency code: ").appendText(currencyCode);
                return false;
            }

            return true;
        }

        @Override
        public void describeTo(Description description) {
            description.appendText("a Transaction with one of currency codes ").appendText(String.join(", ", currencyCodes));
        }
    };
}
```

**Comment by buchen** [comment]
Hey @Nirus2000,

I am not sure what to look at.

The error message from the log
> Failures: 
  KBCGroupNVPDFExtractorTest.testRekeninguittreksel03:268 Imported gross value (USD 60,665.50) and calculated gross value (USD 69,725.55) do not match
Jun 12, 2023, 11:55 AM Sell USD 69,606.12 ISHARES PLC CORE MSC E.M.IM UC Rekeninguittreksel03.txt

is correct, isn't it? The gross value does not match the calculated gross value so that transaction is not consistent.

69,606.12 + 72.80 (taxes) + 46.63 (fees) is a gross value of 69.725,55 which does not fit to the configured gross value of 60665.50 $. That is off by some 9000 $.

About

> new AssertImportActions().check(results, “EUR”, “USD”);

where do I find the failure?

**Comment by Nirus2000** [comment]
HeyHo @buchen 
The "[Debug](https://github.com/portfolio-performance/portfolio/pull/4294/files#diff-8d7df10e6dbd920a6b4cf96f56f21d720b8e087488c5a1b9a9d4ef357759aed8R73-R79)" output is in the console.

The problem is that it is displayed via:
`new AssertImportActions().check(results, “EUR”, “USD”);`
thinks the conversion should be in `USD`, but it is in `EUR`.
It simply calculates incorrectly, as I have one transaction that goes to a `EUR account` and one to a `USD account`.
The correct results are stored in the test case [testRekeninguittreksel03()](https://github.com/portfolio-performance/portfolio/pull/4294/files#diff-dfc5e4a6ddcbd00958db9d6132806be3700043d3fe4f8d259eb12e7a1bb255c6R253-R292).

**Comment by buchen** [comment]
> The correct results are stored in the test case [testRekeninguittreksel03()](https://github.com/portfolio-performance/portfolio/pull/4294/files#diff-dfc5e4a6ddcbd00958db9d6132806be3700043d3fe4f8d259eb12e7a1bb255c6R253-R292).

Looking at the debug output of this test case "03", the transaction is not created correctly.
As you can see, the calculated gross value is 69.725,55 USD.
But that does not fit to the gross value in the unit, which is 60.665,50 USD.

There is no calculation (or currency conversion) at this point in time, because all these values are stored with the transaction directly.

```
DEBUG: transaction: 12.06.2023, 11:55 SELL              USD 69.606,12 ISHARES PLC CORE MSC E.M.IM UC
DEBUG: grossValueUnit: Optional[GROSS_VALUE       USD 60.665,50 EUR 65.046,30 0.932651]
DEBUG: grossValueUnit.get(): GROSS_VALUE       USD 60.665,50 EUR 65.046,30 0.932651
DEBUG: grossValueUnit.get().getForex(): EUR 65.046,30
DEBUG: unitValue: USD 60.665,50
DEBUG: calculatedValue: USD 69.725,55
DEBUG: unitValue.equals(calculatedValue): false
```

**Comment by buchen** [comment]
I think base and term currency code are flipped in the importer (below the changed version).
After applying the change, the values differ by 2 cents (did not check where that comes from, I guess from converting fees and taxes to USD).

```
DEBUG: unitValue: USD 69.743,45
DEBUG: calculatedValue: USD 69.743,43
```


```java
                        .section("fxGross", "baseCurrency", "exchangeRate", "termCurrency").optional() //
                        .match("^.* aan .* (?<fxGross>[\\.,\\d]+) (?<fxCurrency>[\\w]{3})$") //
                        .match("^[\\.,\\d]+ (?<baseCurrency>[\\w]{3}) = (?<exchangeRate>[\\.,\\d]+) (?<termCurrency>[\\w]{3})$") //
                        .assign((t, v) -> {
                            ExtrExchangeRate rate = asExchangeRate(v);
                            type.getCurrentContext().putType(rate);

                            Money fxGross = Money.of(asCurrencyCode(v.get("fxCurrency")), asAmount(v.get("fxGross")));
                            Money gross = rate.convert(t.getAccountTransaction().getCurrencyCode(), fxGross);
                            
                            checkAndSetGrossUnit(gross, fxGross, t, type.getCurrentContext());
                        })
```

**Comment by Nirus2000** [comment]
> > The correct results are stored in the test case [testRekeninguittreksel03()](https://github.com/portfolio-performance/portfolio/pull/4294/files#diff-dfc5e4a6ddcbd00958db9d6132806be3700043d3fe4f8d259eb12e7a1bb255c6R253-R292).
> 
> Looking at the debug output of this test case "03", the transaction is not created correctly. As you can see, the calculated gross value is 69.725,55 USD. But that does not fit to the gross value in the unit, which is 60.665,50 USD.
> 
> There is no calculation (or currency conversion) at this point in time, because all these values are stored with the transaction directly.
> 
> ```
> DEBUG: transaction: 12.06.2023, 11:55 SELL              USD 69.606,12 ISHARES PLC CORE MSC E.M.IM UC
> DEBUG: grossValueUnit: Optional[GROSS_VALUE       USD 60.665,50 EUR 65.046,30 0.932651]
> DEBUG: grossValueUnit.get(): GROSS_VALUE       USD 60.665,50 EUR 65.046,30 0.932651
> DEBUG: grossValueUnit.get().getForex(): EUR 65.046,30
> DEBUG: unitValue: USD 60.665,50
> DEBUG: calculatedValue: USD 69.725,55
> DEBUG: unitValue.equals(calculatedValue): false
> ```

Thx.. done 👍🏻

**Pull request merged**
