### PR TITLE
new PDF Importer for AKF Bank

### PR DESCRIPTION
**Pull request by ZfT2**
new PDF Importer for AKF Bank Kontoauszüge

### CODE REVIEW

**Comment by Nirus2000** [comment]
@ZfT2 
Come on, buddy. ... 
Wouldn't it be an advantage if you used the new test case structure?

**Review by Nirus2000 — CHANGES_REQUESTED** [review]
@ZfT2
Come on, buddy. ...
Wouldn't it be an advantage if you used the new test case structure?

The second part is... to validate the currency....
Please have a look [here](https://github.com/portfolio-performance/portfolio/blob/1d68cbc84e5f7b110671b069df7f44e9cc6a41df/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/DkbPDFExtractor.java#L685:L711)  + [here](https://github.com/portfolio-performance/portfolio/blob/1d68cbc84e5f7b110671b069df7f44e9cc6a41df/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/DkbPDFExtractor.java#L724) and implement it in your source.

**Comment by Nirus2000** [comment]
> You mean the naming for the test files an test methods? Sorry I copied and pasted it from another recent importer... :)

We understand that, but PP also continues to develop the source code... ;-)

**Comment by ZfT2** [comment]
like this? :)

**Comment by Nirus2000** [comment]
No... like this test case.

https://github.com/portfolio-performance/portfolio/blob/master/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/dkb/DkbPDFExtractorTest.java#L4367

**Comment by ZfT2** [comment]
The AKF Bank doensn't offer a Girokonto as far as I know,, so should it really be named as testGiroKontoauszug...?
My Test files are based from Tagesgeld Transaktions...

**Comment by Nirus2000** [comment]
Das ist mir klar, dass kein Girokonto ist... es geht um die Struktur und den Aufbau der test cases... diese sind kleine, smarter und kürzer...

**Comment by buchen** [comment]
> The AKF Bank doensn't offer a Girokonto as far as I know

@ZfT2, I think what @Nirus2000 wants to say that there is simpler and less verbose way to write the assert statements in unit tests.

For example:

```java
        assertThat(results,
                hasItem(interest(
                        hasDate("2023-06-30"),
                        hasAmount("EUR", 302.54),
                        hasNote("Abrechnungszeitraum vom 01.04.2023 bis 30.06.2023"))));
```

But obviously both methods continue to work. As Nirus had no other comments, I took the liberty to merge the importer :-) thanks.

**Pull request merged**
